[package]
name = "api-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "app", "entity", "migration"]

[dependencies]
app = { path = "app" }
entity = { path = "entity" }
migration = { path = "migration" }
